version: '3.7'

services:
  pg:
    restart: always
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: tax
      POSTGRES_DB: tax_dev
      POSTGRES_PASSWORD: tax
      TZ: Europe/Moscow
    command:
      - 'postgres'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    restart: always
    context: ./API/API/Dockerfile

volumes:
  pg_data: